/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ConsoleRouteRouteImport } from './../routes/console/route'
import { Route as PublicRouteRouteImport } from './../routes/_public/route'
import { Route as AuthRouteRouteImport } from './../routes/_auth/route'
import { Route as ConsoleIndexRouteImport } from './../routes/console/index'
import { Route as PublicIndexRouteImport } from './../routes/_public/index'
import { Route as PublicTermsRouteImport } from './../routes/_public/terms'
import { Route as PublicServicesRouteImport } from './../routes/_public/services'
import { Route as PublicPrivacyRouteImport } from './../routes/_public/privacy'
import { Route as PublicDebug500RouteImport } from './../routes/_public/debug-500'
import { Route as PublicContactRouteImport } from './../routes/_public/contact'
import { Route as AuthVerifyEmailRouteImport } from './../routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './../routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './../routes/_auth/register'
import { Route as AuthLoginRouteImport } from './../routes/_auth/login'
import { Route as ConsoleMeIndexRouteImport } from './../routes/console/me/index'
import { Route as ConsoleManagementsIndexRouteImport } from './../routes/console/managements/index'
import { Route as AuthTwoFactorIndexRouteImport } from './../routes/_auth/two-factor.index'
import { Route as ConsoleMeNotificationsRouteImport } from './../routes/console/me/notifications'
import { Route as ConsoleManagementsPoliciesRouteImport } from './../routes/console/managements/policies'
import { Route as ConsoleFeature2Page2RouteImport } from './../routes/console/feature2/page2'
import { Route as ConsoleFeature2Page1RouteImport } from './../routes/console/feature2/page1'
import { Route as ConsoleFeature1Page2RouteImport } from './../routes/console/feature1/page2'
import { Route as ConsoleFeature1Page1RouteImport } from './../routes/console/feature1/page1'
import { Route as AuthTwoFactorRecoveryRouteImport } from './../routes/_auth/two-factor.recovery'
import { Route as AuthTwoFactorAppRouteImport } from './../routes/_auth/two-factor.app'
import { Route as ConsoleMeSettingsIndexRouteImport } from './../routes/console/me/settings/index'
import { Route as ConsoleManagementsUsersIndexRouteImport } from './../routes/console/managements/users/index'
import { Route as ConsoleMeSettingsSecurityRouteImport } from './../routes/console/me/settings/security'
import { Route as ConsoleMeSettingsPasswordRouteImport } from './../routes/console/me/settings/password'
import { Route as ConsoleMeSettingsNotificationsRouteImport } from './../routes/console/me/settings/notifications'
import { Route as ConsoleMeSettingsConnectionsRouteImport } from './../routes/console/me/settings/connections'
import { Route as ConsoleMeSettingsAppearanceRouteImport } from './../routes/console/me/settings/appearance'
import { Route as ConsoleManagementsUsersImportRouteImport } from './../routes/console/managements/users/import'
import { Route as ConsoleManagementsUsersExportRouteImport } from './../routes/console/managements/users/export'
import { Route as ConsoleManagementsUsersCreateRouteImport } from './../routes/console/managements/users/create'
import { Route as ConsoleManagementsUsersUserIdIndexRouteImport } from './../routes/console/managements/users/$userId.index'
import { Route as ConsoleManagementsUsersUserIdEditRouteImport } from './../routes/console/managements/users/$userId.edit'

const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDebug500Route = PublicDebug500RouteImport.update({
  id: '/debug-500',
  path: '/debug-500',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ConsoleMeIndexRoute = ConsoleMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleManagementsIndexRoute = ConsoleManagementsIndexRouteImport.update({
  id: '/managements/',
  path: '/managements/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ConsoleMeNotificationsRoute = ConsoleMeNotificationsRouteImport.update({
  id: '/me/notifications',
  path: '/me/notifications',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleManagementsPoliciesRoute =
  ConsoleManagementsPoliciesRouteImport.update({
    id: '/managements/policies',
    path: '/managements/policies',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleFeature2Page2Route = ConsoleFeature2Page2RouteImport.update({
  id: '/feature2/page2',
  path: '/feature2/page2',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFeature2Page1Route = ConsoleFeature2Page1RouteImport.update({
  id: '/feature2/page1',
  path: '/feature2/page1',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFeature1Page2Route = ConsoleFeature1Page2RouteImport.update({
  id: '/feature1/page2',
  path: '/feature1/page2',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFeature1Page1Route = ConsoleFeature1Page1RouteImport.update({
  id: '/feature1/page1',
  path: '/feature1/page1',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthTwoFactorRecoveryRoute = AuthTwoFactorRecoveryRouteImport.update({
  id: '/two-factor/recovery',
  path: '/two-factor/recovery',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorAppRoute = AuthTwoFactorAppRouteImport.update({
  id: '/two-factor/app',
  path: '/two-factor/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ConsoleMeSettingsIndexRoute = ConsoleMeSettingsIndexRouteImport.update({
  id: '/me/settings/',
  path: '/me/settings/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleManagementsUsersIndexRoute =
  ConsoleManagementsUsersIndexRouteImport.update({
    id: '/managements/users/',
    path: '/managements/users/',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleMeSettingsSecurityRoute =
  ConsoleMeSettingsSecurityRouteImport.update({
    id: '/me/settings/security',
    path: '/me/settings/security',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleMeSettingsPasswordRoute =
  ConsoleMeSettingsPasswordRouteImport.update({
    id: '/me/settings/password',
    path: '/me/settings/password',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleMeSettingsNotificationsRoute =
  ConsoleMeSettingsNotificationsRouteImport.update({
    id: '/me/settings/notifications',
    path: '/me/settings/notifications',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleMeSettingsConnectionsRoute =
  ConsoleMeSettingsConnectionsRouteImport.update({
    id: '/me/settings/connections',
    path: '/me/settings/connections',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleMeSettingsAppearanceRoute =
  ConsoleMeSettingsAppearanceRouteImport.update({
    id: '/me/settings/appearance',
    path: '/me/settings/appearance',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleManagementsUsersImportRoute =
  ConsoleManagementsUsersImportRouteImport.update({
    id: '/managements/users/import',
    path: '/managements/users/import',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleManagementsUsersExportRoute =
  ConsoleManagementsUsersExportRouteImport.update({
    id: '/managements/users/export',
    path: '/managements/users/export',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleManagementsUsersCreateRoute =
  ConsoleManagementsUsersCreateRouteImport.update({
    id: '/managements/users/create',
    path: '/managements/users/create',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleManagementsUsersUserIdIndexRoute =
  ConsoleManagementsUsersUserIdIndexRouteImport.update({
    id: '/managements/users/$userId/',
    path: '/managements/users/$userId/',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleManagementsUsersUserIdEditRoute =
  ConsoleManagementsUsersUserIdEditRouteImport.update({
    id: '/managements/users/$userId/edit',
    path: '/managements/users/$userId/edit',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/contact': typeof PublicContactRoute
  '/debug-500': typeof PublicDebug500Route
  '/privacy': typeof PublicPrivacyRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/console/': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/console/feature1/page1': typeof ConsoleFeature1Page1Route
  '/console/feature1/page2': typeof ConsoleFeature1Page2Route
  '/console/feature2/page1': typeof ConsoleFeature2Page1Route
  '/console/feature2/page2': typeof ConsoleFeature2Page2Route
  '/console/managements/policies': typeof ConsoleManagementsPoliciesRoute
  '/console/me/notifications': typeof ConsoleMeNotificationsRoute
  '/two-factor/': typeof AuthTwoFactorIndexRoute
  '/console/managements/': typeof ConsoleManagementsIndexRoute
  '/console/me/': typeof ConsoleMeIndexRoute
  '/console/managements/users/create': typeof ConsoleManagementsUsersCreateRoute
  '/console/managements/users/export': typeof ConsoleManagementsUsersExportRoute
  '/console/managements/users/import': typeof ConsoleManagementsUsersImportRoute
  '/console/me/settings/appearance': typeof ConsoleMeSettingsAppearanceRoute
  '/console/me/settings/connections': typeof ConsoleMeSettingsConnectionsRoute
  '/console/me/settings/notifications': typeof ConsoleMeSettingsNotificationsRoute
  '/console/me/settings/password': typeof ConsoleMeSettingsPasswordRoute
  '/console/me/settings/security': typeof ConsoleMeSettingsSecurityRoute
  '/console/managements/users/': typeof ConsoleManagementsUsersIndexRoute
  '/console/me/settings/': typeof ConsoleMeSettingsIndexRoute
  '/console/managements/users/$userId/edit': typeof ConsoleManagementsUsersUserIdEditRoute
  '/console/managements/users/$userId/': typeof ConsoleManagementsUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/contact': typeof PublicContactRoute
  '/debug-500': typeof PublicDebug500Route
  '/privacy': typeof PublicPrivacyRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/console': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/console/feature1/page1': typeof ConsoleFeature1Page1Route
  '/console/feature1/page2': typeof ConsoleFeature1Page2Route
  '/console/feature2/page1': typeof ConsoleFeature2Page1Route
  '/console/feature2/page2': typeof ConsoleFeature2Page2Route
  '/console/managements/policies': typeof ConsoleManagementsPoliciesRoute
  '/console/me/notifications': typeof ConsoleMeNotificationsRoute
  '/two-factor': typeof AuthTwoFactorIndexRoute
  '/console/managements': typeof ConsoleManagementsIndexRoute
  '/console/me': typeof ConsoleMeIndexRoute
  '/console/managements/users/create': typeof ConsoleManagementsUsersCreateRoute
  '/console/managements/users/export': typeof ConsoleManagementsUsersExportRoute
  '/console/managements/users/import': typeof ConsoleManagementsUsersImportRoute
  '/console/me/settings/appearance': typeof ConsoleMeSettingsAppearanceRoute
  '/console/me/settings/connections': typeof ConsoleMeSettingsConnectionsRoute
  '/console/me/settings/notifications': typeof ConsoleMeSettingsNotificationsRoute
  '/console/me/settings/password': typeof ConsoleMeSettingsPasswordRoute
  '/console/me/settings/security': typeof ConsoleMeSettingsSecurityRoute
  '/console/managements/users': typeof ConsoleManagementsUsersIndexRoute
  '/console/me/settings': typeof ConsoleMeSettingsIndexRoute
  '/console/managements/users/$userId/edit': typeof ConsoleManagementsUsersUserIdEditRoute
  '/console/managements/users/$userId': typeof ConsoleManagementsUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/debug-500': typeof PublicDebug500Route
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/_auth/two-factor/app': typeof AuthTwoFactorAppRoute
  '/_auth/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/console/feature1/page1': typeof ConsoleFeature1Page1Route
  '/console/feature1/page2': typeof ConsoleFeature1Page2Route
  '/console/feature2/page1': typeof ConsoleFeature2Page1Route
  '/console/feature2/page2': typeof ConsoleFeature2Page2Route
  '/console/managements/policies': typeof ConsoleManagementsPoliciesRoute
  '/console/me/notifications': typeof ConsoleMeNotificationsRoute
  '/_auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/console/managements/': typeof ConsoleManagementsIndexRoute
  '/console/me/': typeof ConsoleMeIndexRoute
  '/console/managements/users/create': typeof ConsoleManagementsUsersCreateRoute
  '/console/managements/users/export': typeof ConsoleManagementsUsersExportRoute
  '/console/managements/users/import': typeof ConsoleManagementsUsersImportRoute
  '/console/me/settings/appearance': typeof ConsoleMeSettingsAppearanceRoute
  '/console/me/settings/connections': typeof ConsoleMeSettingsConnectionsRoute
  '/console/me/settings/notifications': typeof ConsoleMeSettingsNotificationsRoute
  '/console/me/settings/password': typeof ConsoleMeSettingsPasswordRoute
  '/console/me/settings/security': typeof ConsoleMeSettingsSecurityRoute
  '/console/managements/users/': typeof ConsoleManagementsUsersIndexRoute
  '/console/me/settings/': typeof ConsoleMeSettingsIndexRoute
  '/console/managements/users/$userId/edit': typeof ConsoleManagementsUsersUserIdEditRoute
  '/console/managements/users/$userId/': typeof ConsoleManagementsUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/contact'
    | '/debug-500'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/console/'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/console/feature1/page1'
    | '/console/feature1/page2'
    | '/console/feature2/page1'
    | '/console/feature2/page2'
    | '/console/managements/policies'
    | '/console/me/notifications'
    | '/two-factor/'
    | '/console/managements/'
    | '/console/me/'
    | '/console/managements/users/create'
    | '/console/managements/users/export'
    | '/console/managements/users/import'
    | '/console/me/settings/appearance'
    | '/console/me/settings/connections'
    | '/console/me/settings/notifications'
    | '/console/me/settings/password'
    | '/console/me/settings/security'
    | '/console/managements/users/'
    | '/console/me/settings/'
    | '/console/managements/users/$userId/edit'
    | '/console/managements/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/contact'
    | '/debug-500'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/console'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/console/feature1/page1'
    | '/console/feature1/page2'
    | '/console/feature2/page1'
    | '/console/feature2/page2'
    | '/console/managements/policies'
    | '/console/me/notifications'
    | '/two-factor'
    | '/console/managements'
    | '/console/me'
    | '/console/managements/users/create'
    | '/console/managements/users/export'
    | '/console/managements/users/import'
    | '/console/me/settings/appearance'
    | '/console/me/settings/connections'
    | '/console/me/settings/notifications'
    | '/console/me/settings/password'
    | '/console/me/settings/security'
    | '/console/managements/users'
    | '/console/me/settings'
    | '/console/managements/users/$userId/edit'
    | '/console/managements/users/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/console'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_public/contact'
    | '/_public/debug-500'
    | '/_public/privacy'
    | '/_public/services'
    | '/_public/terms'
    | '/_public/'
    | '/console/'
    | '/_auth/two-factor/app'
    | '/_auth/two-factor/recovery'
    | '/console/feature1/page1'
    | '/console/feature1/page2'
    | '/console/feature2/page1'
    | '/console/feature2/page2'
    | '/console/managements/policies'
    | '/console/me/notifications'
    | '/_auth/two-factor/'
    | '/console/managements/'
    | '/console/me/'
    | '/console/managements/users/create'
    | '/console/managements/users/export'
    | '/console/managements/users/import'
    | '/console/me/settings/appearance'
    | '/console/me/settings/connections'
    | '/console/me/settings/notifications'
    | '/console/me/settings/password'
    | '/console/me/settings/security'
    | '/console/managements/users/'
    | '/console/me/settings/'
    | '/console/managements/users/$userId/edit'
    | '/console/managements/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/debug-500': {
      id: '/_public/debug-500'
      path: '/debug-500'
      fullPath: '/debug-500'
      preLoaderRoute: typeof PublicDebug500RouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/console/me/': {
      id: '/console/me/'
      path: '/me'
      fullPath: '/console/me/'
      preLoaderRoute: typeof ConsoleMeIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/': {
      id: '/console/managements/'
      path: '/managements'
      fullPath: '/console/managements/'
      preLoaderRoute: typeof ConsoleManagementsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_auth/two-factor/': {
      id: '/_auth/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/console/me/notifications': {
      id: '/console/me/notifications'
      path: '/me/notifications'
      fullPath: '/console/me/notifications'
      preLoaderRoute: typeof ConsoleMeNotificationsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/policies': {
      id: '/console/managements/policies'
      path: '/managements/policies'
      fullPath: '/console/managements/policies'
      preLoaderRoute: typeof ConsoleManagementsPoliciesRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature2/page2': {
      id: '/console/feature2/page2'
      path: '/feature2/page2'
      fullPath: '/console/feature2/page2'
      preLoaderRoute: typeof ConsoleFeature2Page2RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature2/page1': {
      id: '/console/feature2/page1'
      path: '/feature2/page1'
      fullPath: '/console/feature2/page1'
      preLoaderRoute: typeof ConsoleFeature2Page1RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature1/page2': {
      id: '/console/feature1/page2'
      path: '/feature1/page2'
      fullPath: '/console/feature1/page2'
      preLoaderRoute: typeof ConsoleFeature1Page2RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature1/page1': {
      id: '/console/feature1/page1'
      path: '/feature1/page1'
      fullPath: '/console/feature1/page1'
      preLoaderRoute: typeof ConsoleFeature1Page1RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_auth/two-factor/recovery': {
      id: '/_auth/two-factor/recovery'
      path: '/two-factor/recovery'
      fullPath: '/two-factor/recovery'
      preLoaderRoute: typeof AuthTwoFactorRecoveryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/two-factor/app': {
      id: '/_auth/two-factor/app'
      path: '/two-factor/app'
      fullPath: '/two-factor/app'
      preLoaderRoute: typeof AuthTwoFactorAppRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/console/me/settings/': {
      id: '/console/me/settings/'
      path: '/me/settings'
      fullPath: '/console/me/settings/'
      preLoaderRoute: typeof ConsoleMeSettingsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users/': {
      id: '/console/managements/users/'
      path: '/managements/users'
      fullPath: '/console/managements/users/'
      preLoaderRoute: typeof ConsoleManagementsUsersIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/me/settings/security': {
      id: '/console/me/settings/security'
      path: '/me/settings/security'
      fullPath: '/console/me/settings/security'
      preLoaderRoute: typeof ConsoleMeSettingsSecurityRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/me/settings/password': {
      id: '/console/me/settings/password'
      path: '/me/settings/password'
      fullPath: '/console/me/settings/password'
      preLoaderRoute: typeof ConsoleMeSettingsPasswordRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/me/settings/notifications': {
      id: '/console/me/settings/notifications'
      path: '/me/settings/notifications'
      fullPath: '/console/me/settings/notifications'
      preLoaderRoute: typeof ConsoleMeSettingsNotificationsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/me/settings/connections': {
      id: '/console/me/settings/connections'
      path: '/me/settings/connections'
      fullPath: '/console/me/settings/connections'
      preLoaderRoute: typeof ConsoleMeSettingsConnectionsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/me/settings/appearance': {
      id: '/console/me/settings/appearance'
      path: '/me/settings/appearance'
      fullPath: '/console/me/settings/appearance'
      preLoaderRoute: typeof ConsoleMeSettingsAppearanceRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users/import': {
      id: '/console/managements/users/import'
      path: '/managements/users/import'
      fullPath: '/console/managements/users/import'
      preLoaderRoute: typeof ConsoleManagementsUsersImportRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users/export': {
      id: '/console/managements/users/export'
      path: '/managements/users/export'
      fullPath: '/console/managements/users/export'
      preLoaderRoute: typeof ConsoleManagementsUsersExportRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users/create': {
      id: '/console/managements/users/create'
      path: '/managements/users/create'
      fullPath: '/console/managements/users/create'
      preLoaderRoute: typeof ConsoleManagementsUsersCreateRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users/$userId/': {
      id: '/console/managements/users/$userId/'
      path: '/managements/users/$userId'
      fullPath: '/console/managements/users/$userId/'
      preLoaderRoute: typeof ConsoleManagementsUsersUserIdIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users/$userId/edit': {
      id: '/console/managements/users/$userId/edit'
      path: '/managements/users/$userId/edit'
      fullPath: '/console/managements/users/$userId/edit'
      preLoaderRoute: typeof ConsoleManagementsUsersUserIdEditRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthTwoFactorAppRoute: typeof AuthTwoFactorAppRoute
  AuthTwoFactorRecoveryRoute: typeof AuthTwoFactorRecoveryRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthTwoFactorAppRoute: AuthTwoFactorAppRoute,
  AuthTwoFactorRecoveryRoute: AuthTwoFactorRecoveryRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicDebug500Route: typeof PublicDebug500Route
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicDebug500Route: PublicDebug500Route,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleFeature1Page1Route: typeof ConsoleFeature1Page1Route
  ConsoleFeature1Page2Route: typeof ConsoleFeature1Page2Route
  ConsoleFeature2Page1Route: typeof ConsoleFeature2Page1Route
  ConsoleFeature2Page2Route: typeof ConsoleFeature2Page2Route
  ConsoleManagementsPoliciesRoute: typeof ConsoleManagementsPoliciesRoute
  ConsoleMeNotificationsRoute: typeof ConsoleMeNotificationsRoute
  ConsoleManagementsIndexRoute: typeof ConsoleManagementsIndexRoute
  ConsoleMeIndexRoute: typeof ConsoleMeIndexRoute
  ConsoleManagementsUsersCreateRoute: typeof ConsoleManagementsUsersCreateRoute
  ConsoleManagementsUsersExportRoute: typeof ConsoleManagementsUsersExportRoute
  ConsoleManagementsUsersImportRoute: typeof ConsoleManagementsUsersImportRoute
  ConsoleMeSettingsAppearanceRoute: typeof ConsoleMeSettingsAppearanceRoute
  ConsoleMeSettingsConnectionsRoute: typeof ConsoleMeSettingsConnectionsRoute
  ConsoleMeSettingsNotificationsRoute: typeof ConsoleMeSettingsNotificationsRoute
  ConsoleMeSettingsPasswordRoute: typeof ConsoleMeSettingsPasswordRoute
  ConsoleMeSettingsSecurityRoute: typeof ConsoleMeSettingsSecurityRoute
  ConsoleManagementsUsersIndexRoute: typeof ConsoleManagementsUsersIndexRoute
  ConsoleMeSettingsIndexRoute: typeof ConsoleMeSettingsIndexRoute
  ConsoleManagementsUsersUserIdEditRoute: typeof ConsoleManagementsUsersUserIdEditRoute
  ConsoleManagementsUsersUserIdIndexRoute: typeof ConsoleManagementsUsersUserIdIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleFeature1Page1Route: ConsoleFeature1Page1Route,
  ConsoleFeature1Page2Route: ConsoleFeature1Page2Route,
  ConsoleFeature2Page1Route: ConsoleFeature2Page1Route,
  ConsoleFeature2Page2Route: ConsoleFeature2Page2Route,
  ConsoleManagementsPoliciesRoute: ConsoleManagementsPoliciesRoute,
  ConsoleMeNotificationsRoute: ConsoleMeNotificationsRoute,
  ConsoleManagementsIndexRoute: ConsoleManagementsIndexRoute,
  ConsoleMeIndexRoute: ConsoleMeIndexRoute,
  ConsoleManagementsUsersCreateRoute: ConsoleManagementsUsersCreateRoute,
  ConsoleManagementsUsersExportRoute: ConsoleManagementsUsersExportRoute,
  ConsoleManagementsUsersImportRoute: ConsoleManagementsUsersImportRoute,
  ConsoleMeSettingsAppearanceRoute: ConsoleMeSettingsAppearanceRoute,
  ConsoleMeSettingsConnectionsRoute: ConsoleMeSettingsConnectionsRoute,
  ConsoleMeSettingsNotificationsRoute: ConsoleMeSettingsNotificationsRoute,
  ConsoleMeSettingsPasswordRoute: ConsoleMeSettingsPasswordRoute,
  ConsoleMeSettingsSecurityRoute: ConsoleMeSettingsSecurityRoute,
  ConsoleManagementsUsersIndexRoute: ConsoleManagementsUsersIndexRoute,
  ConsoleMeSettingsIndexRoute: ConsoleMeSettingsIndexRoute,
  ConsoleManagementsUsersUserIdEditRoute:
    ConsoleManagementsUsersUserIdEditRoute,
  ConsoleManagementsUsersUserIdIndexRoute:
    ConsoleManagementsUsersUserIdIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
