/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ConsoleRouteRouteImport } from './../routes/console/route'
import { Route as PublicRouteRouteImport } from './../routes/_public/route'
import { Route as AuthRouteRouteImport } from './../routes/_auth/route'
import { Route as ConsoleIndexRouteImport } from './../routes/console/index'
import { Route as PublicIndexRouteImport } from './../routes/_public/index'
import { Route as PublicTermsRouteImport } from './../routes/_public/terms'
import { Route as PublicServicesRouteImport } from './../routes/_public/services'
import { Route as PublicPrivacyRouteImport } from './../routes/_public/privacy'
import { Route as PublicDebug500RouteImport } from './../routes/_public/debug-500'
import { Route as PublicContactRouteImport } from './../routes/_public/contact'
import { Route as AuthVerifyEmailRouteImport } from './../routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './../routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './../routes/_auth/register'
import { Route as AuthLoginRouteImport } from './../routes/_auth/login'
import { Route as AuthTwoFactorIndexRouteImport } from './../routes/_auth/two-factor.index'
import { Route as ConsoleMeProfileRouteImport } from './../routes/console/me.profile'
import { Route as ConsoleMeNotificationsRouteImport } from './../routes/console/me.notifications'
import { Route as ConsoleManagementsUsersRouteImport } from './../routes/console/managements.users'
import { Route as ConsoleManagementsPoliciesRouteImport } from './../routes/console/managements.policies'
import { Route as ConsoleFeature2Page2RouteImport } from './../routes/console/feature2.page2'
import { Route as ConsoleFeature2Page1RouteImport } from './../routes/console/feature2.page1'
import { Route as ConsoleFeature1Page2RouteImport } from './../routes/console/feature1.page2'
import { Route as ConsoleFeature1Page1RouteImport } from './../routes/console/feature1.page1'
import { Route as AuthTwoFactorRecoveryRouteImport } from './../routes/_auth/two-factor.recovery'
import { Route as AuthTwoFactorAppRouteImport } from './../routes/_auth/two-factor.app'

const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDebug500Route = PublicDebug500RouteImport.update({
  id: '/debug-500',
  path: '/debug-500',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ConsoleMeProfileRoute = ConsoleMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMeNotificationsRoute = ConsoleMeNotificationsRouteImport.update({
  id: '/me/notifications',
  path: '/me/notifications',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleManagementsUsersRoute = ConsoleManagementsUsersRouteImport.update({
  id: '/managements/users',
  path: '/managements/users',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleManagementsPoliciesRoute =
  ConsoleManagementsPoliciesRouteImport.update({
    id: '/managements/policies',
    path: '/managements/policies',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleFeature2Page2Route = ConsoleFeature2Page2RouteImport.update({
  id: '/feature2/page2',
  path: '/feature2/page2',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFeature2Page1Route = ConsoleFeature2Page1RouteImport.update({
  id: '/feature2/page1',
  path: '/feature2/page1',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFeature1Page2Route = ConsoleFeature1Page2RouteImport.update({
  id: '/feature1/page2',
  path: '/feature1/page2',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFeature1Page1Route = ConsoleFeature1Page1RouteImport.update({
  id: '/feature1/page1',
  path: '/feature1/page1',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthTwoFactorRecoveryRoute = AuthTwoFactorRecoveryRouteImport.update({
  id: '/two-factor/recovery',
  path: '/two-factor/recovery',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorAppRoute = AuthTwoFactorAppRouteImport.update({
  id: '/two-factor/app',
  path: '/two-factor/app',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/contact': typeof PublicContactRoute
  '/debug-500': typeof PublicDebug500Route
  '/privacy': typeof PublicPrivacyRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/console/': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/console/feature1/page1': typeof ConsoleFeature1Page1Route
  '/console/feature1/page2': typeof ConsoleFeature1Page2Route
  '/console/feature2/page1': typeof ConsoleFeature2Page1Route
  '/console/feature2/page2': typeof ConsoleFeature2Page2Route
  '/console/managements/policies': typeof ConsoleManagementsPoliciesRoute
  '/console/managements/users': typeof ConsoleManagementsUsersRoute
  '/console/me/notifications': typeof ConsoleMeNotificationsRoute
  '/console/me/profile': typeof ConsoleMeProfileRoute
  '/two-factor/': typeof AuthTwoFactorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/contact': typeof PublicContactRoute
  '/debug-500': typeof PublicDebug500Route
  '/privacy': typeof PublicPrivacyRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/console': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/console/feature1/page1': typeof ConsoleFeature1Page1Route
  '/console/feature1/page2': typeof ConsoleFeature1Page2Route
  '/console/feature2/page1': typeof ConsoleFeature2Page1Route
  '/console/feature2/page2': typeof ConsoleFeature2Page2Route
  '/console/managements/policies': typeof ConsoleManagementsPoliciesRoute
  '/console/managements/users': typeof ConsoleManagementsUsersRoute
  '/console/me/notifications': typeof ConsoleMeNotificationsRoute
  '/console/me/profile': typeof ConsoleMeProfileRoute
  '/two-factor': typeof AuthTwoFactorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/debug-500': typeof PublicDebug500Route
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/_auth/two-factor/app': typeof AuthTwoFactorAppRoute
  '/_auth/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/console/feature1/page1': typeof ConsoleFeature1Page1Route
  '/console/feature1/page2': typeof ConsoleFeature1Page2Route
  '/console/feature2/page1': typeof ConsoleFeature2Page1Route
  '/console/feature2/page2': typeof ConsoleFeature2Page2Route
  '/console/managements/policies': typeof ConsoleManagementsPoliciesRoute
  '/console/managements/users': typeof ConsoleManagementsUsersRoute
  '/console/me/notifications': typeof ConsoleMeNotificationsRoute
  '/console/me/profile': typeof ConsoleMeProfileRoute
  '/_auth/two-factor/': typeof AuthTwoFactorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/contact'
    | '/debug-500'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/console/'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/console/feature1/page1'
    | '/console/feature1/page2'
    | '/console/feature2/page1'
    | '/console/feature2/page2'
    | '/console/managements/policies'
    | '/console/managements/users'
    | '/console/me/notifications'
    | '/console/me/profile'
    | '/two-factor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/contact'
    | '/debug-500'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/console'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/console/feature1/page1'
    | '/console/feature1/page2'
    | '/console/feature2/page1'
    | '/console/feature2/page2'
    | '/console/managements/policies'
    | '/console/managements/users'
    | '/console/me/notifications'
    | '/console/me/profile'
    | '/two-factor'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/console'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_public/contact'
    | '/_public/debug-500'
    | '/_public/privacy'
    | '/_public/services'
    | '/_public/terms'
    | '/_public/'
    | '/console/'
    | '/_auth/two-factor/app'
    | '/_auth/two-factor/recovery'
    | '/console/feature1/page1'
    | '/console/feature1/page2'
    | '/console/feature2/page1'
    | '/console/feature2/page2'
    | '/console/managements/policies'
    | '/console/managements/users'
    | '/console/me/notifications'
    | '/console/me/profile'
    | '/_auth/two-factor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/debug-500': {
      id: '/_public/debug-500'
      path: '/debug-500'
      fullPath: '/debug-500'
      preLoaderRoute: typeof PublicDebug500RouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/two-factor/': {
      id: '/_auth/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/console/me/profile': {
      id: '/console/me/profile'
      path: '/me/profile'
      fullPath: '/console/me/profile'
      preLoaderRoute: typeof ConsoleMeProfileRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/me/notifications': {
      id: '/console/me/notifications'
      path: '/me/notifications'
      fullPath: '/console/me/notifications'
      preLoaderRoute: typeof ConsoleMeNotificationsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/users': {
      id: '/console/managements/users'
      path: '/managements/users'
      fullPath: '/console/managements/users'
      preLoaderRoute: typeof ConsoleManagementsUsersRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/managements/policies': {
      id: '/console/managements/policies'
      path: '/managements/policies'
      fullPath: '/console/managements/policies'
      preLoaderRoute: typeof ConsoleManagementsPoliciesRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature2/page2': {
      id: '/console/feature2/page2'
      path: '/feature2/page2'
      fullPath: '/console/feature2/page2'
      preLoaderRoute: typeof ConsoleFeature2Page2RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature2/page1': {
      id: '/console/feature2/page1'
      path: '/feature2/page1'
      fullPath: '/console/feature2/page1'
      preLoaderRoute: typeof ConsoleFeature2Page1RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature1/page2': {
      id: '/console/feature1/page2'
      path: '/feature1/page2'
      fullPath: '/console/feature1/page2'
      preLoaderRoute: typeof ConsoleFeature1Page2RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/feature1/page1': {
      id: '/console/feature1/page1'
      path: '/feature1/page1'
      fullPath: '/console/feature1/page1'
      preLoaderRoute: typeof ConsoleFeature1Page1RouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_auth/two-factor/recovery': {
      id: '/_auth/two-factor/recovery'
      path: '/two-factor/recovery'
      fullPath: '/two-factor/recovery'
      preLoaderRoute: typeof AuthTwoFactorRecoveryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/two-factor/app': {
      id: '/_auth/two-factor/app'
      path: '/two-factor/app'
      fullPath: '/two-factor/app'
      preLoaderRoute: typeof AuthTwoFactorAppRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthTwoFactorAppRoute: typeof AuthTwoFactorAppRoute
  AuthTwoFactorRecoveryRoute: typeof AuthTwoFactorRecoveryRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthTwoFactorAppRoute: AuthTwoFactorAppRoute,
  AuthTwoFactorRecoveryRoute: AuthTwoFactorRecoveryRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicDebug500Route: typeof PublicDebug500Route
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicDebug500Route: PublicDebug500Route,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleFeature1Page1Route: typeof ConsoleFeature1Page1Route
  ConsoleFeature1Page2Route: typeof ConsoleFeature1Page2Route
  ConsoleFeature2Page1Route: typeof ConsoleFeature2Page1Route
  ConsoleFeature2Page2Route: typeof ConsoleFeature2Page2Route
  ConsoleManagementsPoliciesRoute: typeof ConsoleManagementsPoliciesRoute
  ConsoleManagementsUsersRoute: typeof ConsoleManagementsUsersRoute
  ConsoleMeNotificationsRoute: typeof ConsoleMeNotificationsRoute
  ConsoleMeProfileRoute: typeof ConsoleMeProfileRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleFeature1Page1Route: ConsoleFeature1Page1Route,
  ConsoleFeature1Page2Route: ConsoleFeature1Page2Route,
  ConsoleFeature2Page1Route: ConsoleFeature2Page1Route,
  ConsoleFeature2Page2Route: ConsoleFeature2Page2Route,
  ConsoleManagementsPoliciesRoute: ConsoleManagementsPoliciesRoute,
  ConsoleManagementsUsersRoute: ConsoleManagementsUsersRoute,
  ConsoleMeNotificationsRoute: ConsoleMeNotificationsRoute,
  ConsoleMeProfileRoute: ConsoleMeProfileRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
